#!/usr/bin/env bash

# The users you'd like to send a message to
users='^(pfeschla|galord|pjbirr|rlcarpen|mtmille1|loganj|cjsumner|pjdoughe)'

# The different messages available to send
phrases=(
	"Hey, hey you."
	"All hail RMS."
	"<something funny>"
	"Are you sitting on F5? Because your butt is refreshing."
	"Praise Linus Torvalds."
	"There is no cloud, it's just someone else's computer."
	"You can't include <unistd.h> without STUD."
	"Baby you make my stack overflow."
	"chown me you"
	"chmod 69 ~you"
	"*insert cute cat gif here*"
	"Reddit is the front page of the interwebs"
	"PC:MR"
	"Got git?"
	"Can you hear me now?"
	"Thou wayward fool-born miscreant!"
	"You scullion! You rampallian! You fustilarian! I'll tickle your catastrophe!"
	"Thou impertinent beef-witted blind-worm!"
	"The mitochondria is the powerhouse of the cell"
	"guardian > colossus"
	"I <3 forking children"
	"I used to be a programmer like you, then I took a segfault in the main()"
	"#tenacity"
	"#tenashitty"
	"Get git? Got git? Good."
	"Will you be the CPU to my motherboard? Cuz baby I want all your pins inside of me."
	"downloadmorewam.com"
	"Give me a Q! Gimme another Q! Give me yet another Q! Gimme one last Q!!! What does that spell? Fork you!"
	"My love for you is bigger than 2^31 + 1"
	"You've cat to be kitten me right meow."
	"Hakuna your tatas."
	"coreOS are my favorite cookie."
	"Knock knock... Who's there? Recursivity. Recursivity who? Knock knock..."
	"To understand what recursion is, you must first understand recursion."
	"Hip hip[];"
	"175 is hexadecimal AF."
	"We may both be Monitors, but at least I'm not of type Hoare."
	"The only STDs I have are stdin and stdout."
)

online=$(
	who | # Check who's online
	tail -n +1 | # Skip the first line of output
	grep -E $users | # Only want the specified users
	sed -r 's:(\w+)\s+(pts/[0-9]+).*:\1@\2:' # Only want username and TTY
)

for user in $online
do
	# Grab a random phrase
	phrase=${phrases[$RANDOM % ${#phrases[@]}]}
	write $(echo $user | sed 's/@/ /') <<< $phrase
done

exit 0
