#!/bin/bash

# The users you'd like to send a message to
users='^(pfeschla|galord|pjbirr|rlcarpen|mtmille1|loganj)'

# The different messages available to send
phrases=(
	"Hey, hey you."
	"All hail RMS."
	"<something funny>"
	"Are you sitting on F5? Because your butt is refreshing."
	"Praise Linus Torvalds."
	"There is no cloud, it's just someone else's computer."
	"You can't include <unistd.h> without STUD."
	"Baby you make my stack overflow."
	"chown me you"
	"chmod 69 ~you"
	"*insert cute cat gif here*"
	"Reddit is the front page of the interwebs"
	"PC:MR"
	"Got git?"
	"Can you hear me now?"
	"Thou wayward fool-born miscreant!"
	"You scullion! You rampallian! You fustilarian! I'll tickle your catastrophe!"
	"Thou impertinent beef-witted blind-worm!"
)

online=$(
	who | # Check who's online
	tail -n +1 | # Skip the first line of output
	grep -E $users | # Only want the specified users
	sed -r 's:(\w+)\s+(pts/[0-9]+).*:\1@\2:' # Only want username and TTY
)

for user in $online
do
	# Grab a random phrase
	phrase=${phrases[$RANDOM % ${#phrases[@]}]}
	write $(echo $user | sed 's/@/ /') <<< $phrase
done

exit 0
